# Location of collections
collections:
  - meta_chapters
  - comic_topics

exclude:
  - Gemfile
  - README.md

header:
  logo: images-layout/cropped-cover.goetter.0.33web-1.jpg
  sub-title:
    - Stoner Ear Candy Rock
    - zwischen heavy und catchy!
  social:
    - name: Facebook
      url: https://www.facebook.com/deafwolfrocks/
      icon: 2020/images/facebook.png
      priority: 1
    - name: bandcamp
      url: https://deafwolf.bandcamp.com/
      icon: 2020/images/bandcamp-button-bc-circle-black-128.png
      priority: 1
    - name: laut.de
      url: http://www.laut.de/Deaf-Flow
      icon: 2020/images/laut_logo_400x400.png
      priority: 1
    - name: Songick
      url: https://www.songkick.com/artists/10322687-deaf-wolf
      icon: 2024/images/songkick.svg
    - name: Instagram
      url: https://www.instagram.com/deafwolf_rocks/
      icon: 2024/images/instagram.png
    - name: Linktree
      url: https://linktr.ee/deafwolf
      icon: 2024/images/linktree.svg
    - name: YouTube
      url: https://www.youtube.com/@MrDeafWolf
      icon: 2024/images/youtube.png
    - name: Spotify
      url: https://open.spotify.com/artist/6cp45mlXkzgtor8bGozNOB
      icon: 2024/images/spotify.png


# gems:
#  - jekyll-sitemap
#  - jekyll-redirect-from

values:
  alignment: [left,right,top,bottom]
  dimension: [1,2,3,4,5,6,7,8,9]
  sizes: [10,20,30,40,50,60,70,80,90]

# Build settings
markdown: kramdown

# Site settings
title: Deaf Wolf
description: "Logbuch des Kapitäns"
source: ./
destination: web

plugins:
  - jekyll-loading-lazy