# Location of collections
collections:
  - meta_chapters

exclude:
  - Gemfile
  - README.md

header:
  logo: images-layout/cropped-cover.goetter.0.33web-1.jpg
  sub-title:
    - Stoner Ear Candy Rock
    - zwischen heavy und catchy!
  social:
    - name: Facebook
      url: https://www.facebook.com/deafflow/
    - name: bandcamp
      url: https://deafflow.bandcamp.com/
    - name: laut.de
      url: http://www.laut.de/Deaf-Flow

# gems:
#  - jekyll-sitemap
#  - jekyll-redirect-from

values:
  alignment: [left,right,top,bottom]
  dimension: [1,2,3,4,5,6,7,8,9]
  sizes: [10,20,30,40,50,60,70,80,90]

# Build settings
markdown: kramdown

# Site settings
title: Deaf Flow
description: "Logbuch des Kapitäns"
source: ./
destination: web
